language: ruby
rvm:
  - 2.5.3
branches:
  only:
    - master
    - Exo-dev

script:
  - ./run test

before_script:
  - ./bin/rake db:setup
  - psql -c "CREATE USER rails_user WITH PASSWORD 'Qq!2345678';" -U postgres
