#!/usr/bin/env ruby

require_relative "./lib/functions.rb"
$server_ip = "127.0.0.1"
$server_port = 65500

case ARGV.length
  when 1
    if (ARGV[0] == "test")
      exec("./bin/rake test")
    elsif (ARGV[0] == "c")
      exec("./bin/rails c")
    end
    $server_ip = ARGV[0]
  when 2
    $server_ip = ARGV[0]
    $server_port = ARGV[1].to_i
  else
    nothing()
end

exec("./bin/exodus #{$server_ip} #{$server_port}")
