---

- name: "Go to the mines"
  ST: -20
  San: -1
  Cash: 50

- name: "Chill out in the tavern"
  MP: -10
  ST: 10
  San: 1

- name: "Take a typical quest of killing the rat"
  HP: -5
  MP: 30
  ST: 5
  San: -1
  Cash: -20
  Chance: 80

- name: "Go get some wood"
  HP: -5
  MP: -10
  ST: -10
  San: 1
  Cash: 10

- name: "Go on a trip"
  HP: -10
  MP: -50
  ST: -50
  San: 3
  Cash: 100

- name: "Go on a DANGEROUS trip"
  HP: -90
  MP: -90
  ST: -90
  San: -5
  Cash: 1000
  Chance: 20

- name: "Have some sleep"
  HP: 90
  San: -3

- name: "Go to the gachi-gym"
  HP: 20
  ST: -30
  San: 5
  Cash: -50
